site_name: Change to the name of your docs
site_url: https://samlee77.github.io/ST2025/
theme:
  name: material
nav:
  - Home: "index.md"
  - Set 1: "Set-1.md"
  - Set 2: "Set2.md"
  - Set 3: "Set3.md"
  - Troubleshooting: "Troubleshooting.md"
  - Glossary: "Glossary.md"
